### ISSUE TITLE
Appearance of preferences at about:addons in Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [tom-james-watson/breaktimer#10]
A minor cosmetic issue. 

When I first used the about:addons interface to preferences, after using about:addons to enable the extension, it took a few attempts before I realised that there was limited space and a scroll bar: 

![2018-10-20 11 31 25 add-ons manager - waterfox](https://user-images.githubusercontent.com/192271/47254582-64eaf680-d45c-11e8-8c9d-e547caf109ed.png)

(The bar is slightly darker than usual in that shot, only because I pointed at it.)

Before discovering the bar, I imagined that most of the preferences were missing. 

A non-coloured background (instead of the turquoise default) _might_ make the bar more noticeable, but I shouldn't recommend this.  

----

`moz-extension://7744aebd-54f5-4a06-9b10-358b0e882345/templates/settings.html` appears fine :+1: 

![2018-10-20 11 33 15 break timer - settings - waterfox](https://user-images.githubusercontent.com/192271/47254618-b2fffa00-d45c-11e8-8378-364545b4e0ad.png)

– so I wonder, instead of a scrolling UI within limited space at about:addons is it possible to have just a **Preferences** button there, to open the preferences page?

**Comment by tom-james-watson** [comment]
Yes agreed. Its a shame Firefox displays the options page so small. The annoying thing is I would need to have a separate manifest for chrome and Firefox, as changing to what you said would break the options page on chrome. Maybe there's a way to do it without needing to do that.
