### ISSUE TITLE
Resolve Firefox review issues

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/breaktimer#11]
Received this email from Mozilla:

> Details:
> This add-on didn&#39;t pass review because of the following problems:
> 
> 1) We no more allow usage of Angular 1.*, Please migrate to newer  version of Angular.
> 
> 2) Established libraries must be included separately, from their official source, in their original format without any modification (changing the file name does not matter). Please note that only stable releases of are acceptable (not beta, pre, RC, dev etc). Minified versions are better. Please note that third party CDNs are not considered official sources for this purpose.
> There is no need to include .map files for established libraries.
> eg: js/vendor/countdown.min.js
> 
> Please fix them and submit again. Thank you.
> 
> Please note that if add-on contains obfuscated, minified, concatenated or otherwise machine-generated code, the code has not been checked yet and their sources will be required in future updates.
> https://developer.mozilla.org/en-US/Add-ons/Source_Code_Submission
> 
> Please also check the validation results regarding &quot;Unsafe assignment to innerHTML&quot;, &quot;The Function constructor is eval.&quot;, &quot;Unsafe assignment to outerHTML&quot;.

**Comment by cantalupo555** [comment]
This is sad, but we can reverse this.

**Comment by biva** [comment]
Hello, sad to see that it's not on Firefox anymore :( Do you plan to release a new compatible version soon? Available for testing if needed!

**Comment by tom-james-watson** [comment]
It basically would need rewriting and it's just not a priority for me at the moment, unfortunately. If anyone wants to help out with that then it would be much appreciated.

**Comment by dpDesignz** [comment]
What needs to be done to add Firefox support back? I LOVE this app on my Chrome at work but need it on my Firefox Dev edition at my home office when I'm coding. 😄 

I might be able to pitch in with the coding if needed?

**Comment by tom-james-watson** [comment]
The code would need switching to a newer version of Angular. Given the differences between Angular 1 and Angular 2+, this would mean rewriting the app from scratch. If I were to do that I would just rewrite it in React anyway.

However - I have actually started work on what I think is the real solution - I'm going to make a desktop version of BreakTimer, meaning it will not be tied to the browser at all. It will be rewritten from scratch using Electron and React and will be available on Windows, Mac and Linux.

Once there's some decent progress there I will link to the project and, once it's finished, I will encourage users to switch to the new app.

**Comment by tom-james-watson** [comment]
@dpDesignz / @biva - if you would like to be guinea pigs for the new app - you can test out the (beta!) version here - https://github.com/tom-james-watson/breaktimer-app/releases.

Would love to hear some feedback!

**Comment by biva** [comment]
Hi @tom-james-watson 
I'm sorry but I don't remember which addon it is :( Could you please share the description?
Thanks!

**Comment by dpDesignz** [comment]
@tom-james-watson have just installed! Will let you know how I get on over the next week or so. 😄 

My antivirus didn't like the d23... complier file. I just had to approve it.

So it also makes a call to an external IP address. Is this for updates or error logs or...?

The settings dialogue is nice and clean.

I like how it shows "Next Break At" in the menu. Is there any way to show an "approximate" minutes until that time, if not exact?

Looking good so far though. Keep up the good work.

**Comment by tom-james-watson** [comment]
The extension is https://chrome.google.com/webstore/detail/break-timer/hklkdbpicdmlpoiellngedpejjkmapei

**Comment by tom-james-watson** [comment]
Thanks for the feedback! The .exe is not signed at the moment so not surprised it gets flagged. Yeah, any phoning home it does will be to check for updates, which should be to GitHub.

You can't really continuously update the tray to show a proper countdown as the tray icon can flash or the menu will jarringly refresh if you have it open. Maybe doing it once per minute and just showing minutes remaining is a reasonable option.

**Comment by cantalupo555** [comment]
> @dpDesignz / @biva - if you would like to be guinea pigs for the new app - you can test out the (beta!) version here - https://github.com/tom-james-watson/breaktimer-app/releases.
> 
> Would love to hear some feedback!

Hello, I will be testing your new project on my linux distribution.
Thank you very much.

**Comment by cantalupo555** [comment]
I can help translate into my language.

**Comment by tom-james-watson** [comment]
The app is available on https://breaktimer.app and is pretty stable now.

I'm not looking to do any translations as managing internationalisation is famously painful. Thanks for the offer though!

**Comment by cantalupo555** [comment]
https://github.com/cantalupo555/repo-solus
`sudo eopkg install breaktimer`

Thank you for your work.
I compiled your project for the Linux distribution called Solus.
https://getsol.us/

![](https://i.imgur.com/1Ib4bOp.png)
