### ISSUE TITLE
idle

### ISSUE THREAD

**Issue by cantalupo555** [tom-james-watson/breaktimer#14]
How does this function work?

![](https://i.imgur.com/R7zcEn0.png)

**Comment by tom-james-watson** [comment]
The extension (in theory) detects that you are inactive using built in extension APIs and, if you are inactive for more than 5 minutes, will reset the break countdown. The idea is it assumes you have been up and about and thus have taken a break of some kind by yourself.

**Comment by cantalupo555** [comment]
Thank you, it works perfectly.
