### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by martin12333** [tom-james-watson/breaktimer#16]
I have read, that

>  this extension has now been deprecated in favour of the standalone desktop application.

But: I am often on a computer, where I cannot install **applications** ... where I can install only Chrome **extensions** ... :disappointed: 

----

(but, anyway, big thanks for the extension :relieved: )

**Comment by tom-james-watson** [comment]
The extension is not going anywhere, but I won't be making any updates or fixes. Maybe if a chrome API update completely breaks it I might fix it, but other than that it is no longer supported, sorry!
