### ISSUE TITLE
You were added to Awesome Humane Tech

### ISSUE THREAD

**Issue by aschrijver** [tom-james-watson/breaktimer#17]
This is just a FYI issue to notify that you were added to the curated awesome-humane-tech in the 'Mindfulness' category, and - if you like that - are now entitled to wear our badge:

[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)

By adding this to the README:

```markdown
[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)
```

https://github.com/humanetech-community/awesome-humane-tech

**Comment by tom-james-watson** [comment]
Thanks for the add. The extension is actually deprecated. I recommend looking at and adding the desktop app instead:

https://github.com/tom-james-watson/breaktimer-app
https://breaktimer.app/

**Comment by aschrijver** [comment]
Oh, thanks for mentioning that. Would you be able to do the update in a PR?

**Edit**: Nice project and site over there, btw :)

**Comment by tom-james-watson** [comment]
https://github.com/humanetech-community/awesome-humane-tech/pull/56/files

**Comment by aschrijver** [comment]
Nice, thanks a bunch! I'll merge, but if the description doesn't fit a single line I have to shorten it (requirement is single line).

If you want you may add the badge on the other project, of course :)
