### ISSUE TITLE
support break length less than 1 minute

### ISSUE THREAD

**Issue by X1011** [tom-james-watson/breaktimer#2]
Hi! 1st of all, thank you for this extension. It's simple and it works.
One thing I would like to see, if you or anyone has a chance to work on it, is to be able to set a break length less than 1 minute. For example, I have heard several sources suggest the 20-20-20 rule: every 20 minutes, look away for 20 seconds at something 20 feet away. I personally follow a 40-40-20 rule, so that it's not so disruptive to my work.

**Comment by tom-james-watson** [comment]
I agree, this would be good to implement.

I have had several requests for the ability to set different kinds of breaks, too. For example, 20 seconds every 20 minutes and then 10 minutes every hour, things like that. I think it would make sense to add this functionality together.

I don't see me having any time available in the foreseeable future to work on this, so I will just leave this issue open here. Hopefully at some point I can come revisit this and make some improvements.

Pull requests are extremely welcome if anybody else feels like working on this.

**Comment by tom-james-watson** [comment]
[breaktimer.zip](https://github.com/tom-james-watson/breaktimer/files/2446229/breaktimer.zip)

Good news - I've got it working on Firefox, though some features are unsupported, namely skipping/postponing breaks. Do you mind please testing the attached version of the app? Thanks!
