### ISSUE TITLE
Limit on postponing the break

### ISSUE THREAD

**Issue by jabranr** [tom-james-watson/breaktimer#3]
Hi, first of all thank you for the great extension! I have recently got myself into keep on postponing the breaks. I wonder if giving an option to set a limit on how many times a break can be postponed a good idea? Cheers

**Comment by tom-james-watson** [comment]
I sometimes finding myself doing the same thing, it's something I've thought about but I'm not quite sure what the best solution is. I'm not convined just directly limiting how many skips you have is the best option as I think that would just get annoying.

I've considered gamifying it somehow - or at least giving some kind of feedback on how well/badly you are doing in terms of taking your breaks.

Open to ideas.

**Comment by jabranr** [comment]
Great. I also don't suggest to directly impose it but rather giving it as an option in settings perhaps. So that it is actually controlled (Off/On) by users themselves. 

Gamifying the experience would also be a good idea. In that case I suggest changing the color intensity (i.e. to red shade step by step on each postpone) for the notification.
