### ISSUE TITLE
Skip and Postpone options are not always shown in Ubuntu 18.04/Gnome

### ISSUE THREAD

**Issue by s0h4m** [tom-james-watson/breaktimer#5]
**System:** Ubuntu 18.04 running Gnome 3.28, chrome stable 68.0.3440.106 and dev 70.0.3521.2
**Problem:** When the break timer notification is shown for the first time (0%) it shows the skip and postpone options, but when the percent increases beyond that (5%, 10% and so on), it stops showing the option to skip and postpone

Screenshot at 0%
![1](https://user-images.githubusercontent.com/17599710/44389906-b1dc4a80-a549-11e8-821b-037e783f1691.jpg)

Screenshot at 5%, 20% and so on showing the absence of the skip and postpone options
![2](https://user-images.githubusercontent.com/17599710/44389913-b86ac200-a549-11e8-9108-62234a541cad.jpg)
![3](https://user-images.githubusercontent.com/17599710/44389921-bacd1c00-a549-11e8-973a-055e4b81a054.jpg)

Also tried this by removing all gnome themes and extensions, same result.

This works fine on chrome os (the only other os I tried)

**Comment by tom-james-watson** [comment]
Thanks for the bug report!

I'd imagine this is a bug with Chrome's implementation of notifications on Ubuntu.

I'll look into whether I can reliably get the OS type, in which case we could not do the percentage updating when on Ubuntu (/all Linux?).

**Comment by tom-james-watson** [comment]
I'll make sure I can recreate the bug myself on my Ubuntu (I haven't used it in a while so I wouldn't have seen it).

**Comment by s0h4m** [comment]
That sounds great, thank you for the great extension, I use it every single day.
Another solution could be to an option to manually disable the percentage update via the settings.

**Comment by s0h4m** [comment]
Any thoughts on how to implement this?

**Comment by tom-james-watson** [comment]
Hi - I have a lot of other work going on at the moment - the problem is more getting round to prioritising this, sorry.

**Comment by tom-james-watson** [comment]
[breaktimer.zip](https://github.com/tom-james-watson/breaktimer/files/2446235/breaktimer.zip)

Hi! I finally got round to checking this out. I've actually decided to just disable the "progress" functionality for everybody, I've heard other users complain of it causing weirdness too. Break notifications still work in the same way, it just won't show the updating progress.

Do you mind testing the attached version of the app to see if it fixes your problem? You should be able to do that by unzipping the file, going to chrome://extensions/, turning Developer Mode on (top right), selecting "Load unpacked" and then opening the folder that was inside the zip. Thanks!

**Comment by tom-james-watson** [comment]
And disable the actual extension first!

**Comment by s0h4m** [comment]
Hi Tom, 

Thanks for taking time out and doing this. I have tested this and it works perfectly on linux (Ubuntu 18.04 + latest chrome stable). Both Skip and Postpone are visible and working. Will be testing this out on mac and chrome os later today.

**Comment by tom-james-watson** [comment]
I've released this update now. You should get it over the next few hours. We've also just added support for Firefox - https://addons.mozilla.org/en-US/firefox/addon/break-timer-app/
