### ISSUE TITLE
Show how many minutes are remaining before the next break on the extension icon

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/breaktimer#6]
See https://stackoverflow.com/questions/5759130/google-chrome-extension-numbers-on-the-icon for how to implement.

Should be fairly easy.

**Comment by grahamperrin** [comment]
Nice idea. I'd like it to be a preference … 

… but not a default because (subtly) from UX and wellbeing perspectives, clock-watching sort of goes against the principle of taking a break :-)
