### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by harogaston** [tom-james-watson/breaktimer#7]
Would it be possible?

**Comment by tom-james-watson** [comment]
Yes, I believe so. I need to check the notifications API is the same, but I would imagine so. I have started using Firefox myself, so I should get round to it soon!

**Comment by harogaston** [comment]
I can help. Never worked on a web extension but I guess I could manage to do so with some guidance.

**Comment by tom-james-watson** [comment]
In theory you should just be able to load the extension straight into
Firefox. I believe they call it load unpacked extension or something like
that. Just select the manifest.json (clone the git repo)

I'd need to bundle the thing up and release it myself, though.

You can maybe test whether it actually works without changes though!

**Comment by harogaston** [comment]
I did that already. Downloaded crx from Chrome Store, rename the extesion to .zip, tweaked the manifest.json (because Firefox complained about some of the fields) and by means of about:debugging used the "Load temporary Addon" functionality. I got the following result:
![screenshot from 2018-10-01 18-23-55](https://user-images.githubusercontent.com/5424205/46316826-93855800-c5a7-11e8-8163-591d7c681c7e.png)

As you see it is not working properly. I didn't try anything beyond this because I was at work.

**Comment by tom-james-watson** [comment]
Thanks for trying. I'll try later this week!

**Comment by harogaston** [comment]
Ok, I'll keep in touch. If I find my way around myself I'll let you know. Thank you.

**Comment by tom-james-watson** [comment]
[breaktimer.zip](https://github.com/tom-james-watson/breaktimer/files/2446229/breaktimer.zip)

Good news - I've got it working on Firefox, though some features are unsupported, namely skipping/postponing breaks. Do you mind please testing the attached version of the app? Thanks!

Edit - to do that, go to about:debugging#addons, press "Load Temporary Addon..." and select the .zip file.

**Comment by tom-james-watson** [comment]
And disable the actual extension first!

**Comment by harogaston** [comment]
Sure, I'll try it out and let you know if something is not right. Thank you!

**Comment by tom-james-watson** [comment]
It's official! https://addons.mozilla.org/en-US/firefox/addon/break-timer-app/
