### ISSUE TITLE
Don't go full screen too soon

### ISSUE THREAD

**Issue by grahamperrin** [tom-james-watson/breaktimer#9]
See below, is there any way to reduce the likelihood of this?

![2018-10-19 04 06 25](https://user-images.githubusercontent.com/192271/47195771-4a7a2580-d355-11e8-95c6-8690535cc52d.png)

(Ignore the right-hand side; it's a dual-display environment.)

TIA

**Comment by tom-james-watson** [comment]
Is this something that has only just started happening?

Does this happen every time a break starts?

Does the same thing happen when you open options?

Also what browser and version?

Thanks!

**Comment by grahamperrin** [comment]
I began using the extension a day or so ago. 

It happens more often than not, only when a break starts. 

Waterfox 56.2.3 on FreeBSD-CURRENT and AFAICT the issue more likely to happen when the OS (not necessarily the browser) is busy. 

I have Firefox 63.0 running but unused, I'll see whether the issue is any less likely to occur in this environment. 

Thanks …

**Comment by tom-james-watson** [comment]
Yeah let me know whether you see the same problem in regular Firefox. Thanks!

**Comment by grahamperrin** [comment]
Early results, with the extension enabled in both (1) Firefox and (2) a minimally-extended instance of Waterfox (whilst using a separate, heavily-extended Waterfox for real browsing, and whilst running things in terminal tabs to keep the system unusually busy): 

- not reproducible.

So maybe the heavily-extended profile is the major contributory factor to the issue. If so, my bad `:-)` but still, it'll be nice if some improvement can be made. 

----

Also, to clarify: what's seen in the opening post is not persistent. It reasonably soon 'gives way' to the proper UI. It's just the full-screen bright background that's a bit too big and glaring, when the _essence_ of the extension is to encourage relaxation. 

I imagine that you can do nothing about the brightness, but if there's a way to not go full-screen until the UI has completely drawn, that'll be very smart. 

Thanks again

**Comment by grahamperrin** [comment]
> … maybe the heavily-extended profile is the major contributory factor to the issue. …

It does seem so.

**Comment by tom-james-watson** [comment]
Thanks for looking into it! I'm not sure why you'd see that to be honest, so I don't know how I'd prevent it, sorry.

**Comment by tom-james-watson** [comment]
I'll leave this issue open for now in case anybody else sees a similar issue on Firefox
